FROM python:3.9-slim

WORKDIR /app

ENV PYTHONUNBUFFERED=1

COPY requirements.dev.txt .

RUN pip install -r requirements.dev.txt

# Set the DJANGO_ENV environment variable (default to development)
ARG DJANGO_ENV=development

ENV DJANGO_ENV=${DJANGO_ENV}

RUN echo "Running in $DJANGO_ENV mode"

COPY . .

EXPOSE 8000

CMD [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]