# Generated by Django 5.0.8 on 2024-11-27 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('published_date', models.DateField()),
                ('no_of_copies', models.IntegerField(default=5)),
                ('current_copies', models.IntegerField(default=5)),
                ('coded_books', models.IntegerField(default=0)),
                ('studentname', models.ManyToManyField(related_name='students', to='Users.student_details')),
            ],
        ),
        migrations.CreateModel(
            name='book_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_no', models.IntegerField(unique=True)),
                ('loaned', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books')),
            ],
        ),
        migrations.CreateModel(
            name='loaned_books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(null=True)),
                ('student_book_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book_code')),
            ],
        ),
    ]
