# Generated by Django 5.0.8 on 2024-09-03 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='loaned_books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(null=True)),
                ('student_book_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book_code')),
            ],
        ),
    ]
